twig:
    globals:
        app_images_profil_directory: '/uploads/images/profil'
        app_images_sortie_directory: '/uploads/images/sortie'

    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]

when@test:
    twig:
        strict_variables: true
